[package]
name = "lancelot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.5"
scraper = "0.20.0"
serde = {version = "1.0.204", features = ["derive"]}
